
FROM	alpine:3.20.3

# RUN		apt update
# RUN		apt upgrade
# RUN		apt install openssl nginx curl vim sudo
# RUN		rm -f /etc/nginx/nginx.conf

# COPY	./config/ngnix.conf /etc/nginx/nginx.conf
# COPY	./tools/nginx_script.sh /nginx_script.sh

# RUN		chmod -R +x /nginx_script.sh

# EXPOSE	443

# ENTRYPOINT [ "./nginx_script.sh" ]